################################# Default configuration ###################
# provide your domain here
baseURL = "https://hr365docs.github.io/HR365_Product/"
# theme
theme = "dot-hugo"
# site title
title = "HR365"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
name = "Facebook"
link = "https://www.facebook.com/hr365apps/"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "https://twitter.com/HR365_HRMS"
  

  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
name = "Linkedin"
link = "https://www.linkedin.com/company/cubic-logics-india-pvt-ltd"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "&copy; 2022-[HR365.](https://www.hr365.us/) [SLA.](https://2020.hr365.us/wp-content/uploads/2020/01/HR365-SLA.pdf) [EULA.](https://www.hr365.us/end-user-license-agreement-eula/) [Privacy Policy.](https://www.hr365.us/privacy/) [Cubic Logics.](https://www.cubiclogics.com" target="_blank" rel="noopener noreferrer)

# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge base"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact/"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = ""
weight = 1

[[Languages.en.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "contact/"
weight = 3

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Employee Directory"
  url = "installation/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Asset Mangement"
  url = "billing-pricing/"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Time-off-manager"
  url = "features/"
  weight = 3

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Time sheet"
  url = "features/"
  weight = 3


################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
copyright = "Copyright &copy; 2021 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.fr.params.banner]
title = "Comment pouvons nous aider?"
subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
bg_image = "images/banner.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé de réponse à votre question?"
content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact/"


################## french navigation #################
[[Languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.fr.menu.main]]
name = "contact"
url = "contact/"
weight = 3

# Dropdown menu
[[Languages.fr.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation/"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing/"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features/"
  weight = 3
